import {StyleSheet} from 'react-native';
import colors from '@src/theme/colors';
import {scale} from 'react-native-size-matters';
import metrics from '@src/theme/metrics';
import {Fonts, Size} from '@src/theme/fonts';

const styles = StyleSheet.create({
  container: {
    backgroundColor: colors.COLOR_6,
    // paddingHorizontal: scale(20),
    height: '100%',
  },
  // section: {
  //   flexDirection: 'row',
  //   alignItems: 'center',
  //   justifyContent: 'space-between',
  //   marginTop: scale(20),
  //   marginBottom: scale(10),
  // },
  // addLeaveIconContainer: {
  //   width: 50,
  //   height: 50,
  //   justifyContent: 'center',
  //   alignItems: 'center',
  //   backgroundColor: colors.COLOR_5,
  //   position: 'absolute',
  //   bottom: 50,
  //   right: 30,
  //   borderRadius: 14,
  //   opacity: 0.6,
  //   zIndex: 9,
  // },
  // addLeaveIcon: {
  //   width: 32,
  //   height: 32,
  // },
  // backButton: {
  //   position: 'absolute',
  //   left: 0,
  //   top: 0,
  //   height: 40,
  //   width: 40,
  //   justifyContent: 'center',
  //   alignItems: 'center',
  // },
  // image: {
  //   width: scale(18),
  //   height: scale(18),
  //   margin: scale(10),
  // },
  // header: {
  //   width: '100%',
  //   alignItems: 'center',
  //   display: 'flex',
  //   justifyContent: 'center',
  //   flexDirection: 'row',
  // },
  // titleText: {
  //   fontSize: Size.font_22,
  //   fontFamily: Fonts.BOLD,
  //   color: colors.BLACK,
  //   textAlign: 'center',
  // },
  // sectionHeadingContainer: {
  //   display: 'flex',
  //   flexDirection: 'row',
  //   justifyContent: 'space-between',
  //   paddingHorizontal: scale(10),
  //   borderBottomWidth: 1,
  //   borderBottomColor: colors.Light_Purple2,
  // },
  // sectionHeading: {
  //   fontSize: Size.font_16,
  //   fontFamily: Fonts.BOLD,
  //   color: colors.BLACK,
  //   borderBottomColor: colors.COLOR_7,
  //   padding: scale(15),
  //   textAlign: 'center',
  // },
  // leaveContainer: {
  //   paddingVertical: scale(16),
  // },
  // leaveHeadingText: {
  //   color: '#615A66',
  //   fontFamily: Fonts.BOLD,
  // },
  // leaveCard: {
  //   display: 'flex',
  //   flexDirection: 'row',
  //   marginTop: scale(10),
  //   padding: scale(16),
  //   justifyContent: 'space-between',
  //   borderWidth: 1,
  //   borderRadius: 20,
  //   borderColor: colors.GRAYBORDER,
  // },
  // leaveCardTitle: {
  //   color: colors.BLACK,
  //   fontFamily: Fonts.BOLD,
  // },
  // leaveCardDate: {
  //   color: '#615A66',
  //   fontFamily: Fonts.MEDIUM,
  // },
  // statusText: {
  //   borderWidth: 1,
  //   borderRadius: 20,
  //   paddingHorizontal: scale(16),
  //   paddingVertical: scale(5),
  //   marginVertical: scale(16),
  //   fontSize: Size.font_12,
  //   fontFamily: Fonts.BOLD,
  // },
  // modalOverlay: {
  //   flex: 1,
  //   backgroundColor: colors.overlay,
  //   justifyContent: 'center',
  //   alignItems: 'center',
  // },
  // bottomSheet: {
  //   height: '80%',
  //   width: '100%',
  //   backgroundColor: colors.COLOR_6,
  //   borderTopLeftRadius: scale(20),
  //   borderTopRightRadius: scale(20),
  //   paddingHorizontal: scale(10),
  // },
  // noLeaveContainar: {
  //   height: 300,
  //   width: '100%',
  //   backgroundColor: colors.WHITE,
  //   marginTop: scale(10),
  //   padding: scale(16),
  //   display: 'flex',
  //   justifyContent: 'center',
  //   alignItems: 'center',
  // },
  // noLeaveHeading1: {
  //   fontFamily: Fonts.MEDIUM,
  //   fontSize: Size.font_16,
  //   color: colors.BLACK,
  //   textAlign: 'center',
  //   marginBottom: scale(20),
  // },
  // noLeaveHeading2: {
  //   fontFamily: Fonts.MEDIUM,
  //   fontSize: Size.font_14,
  //   color: colors.GRAY,
  //   textAlign: 'center',
  //   marginVertical: scale(5),
  // },
  // noLeaveImage: {
  //   height: 200,
  //   width: 250,
  // },
  // descriptionSheet: {
  //   height: '70%',
  //   width: '100%',
  //   backgroundColor: colors.COLOR_6,
  //   borderTopLeftRadius: scale(20),
  //   borderTopRightRadius: scale(20),
  //   paddingHorizontal: scale(10),
  // },
  // contentWrapper: {
  //   paddingHorizontal: scale(16),
  // },
  // leaveStatus: {
  //   fontFamily: Fonts.BOLD,
  //   fontSize: Size.font_20,
  //   color: colors.BLACK,
  //   textAlign: 'center',
  // },
  // reasonForLeaveText: {
  //   fontSize: Size.font_12,
  //   fontFamily: Fonts.BOLD,
  //   color: colors.GRAYTEXT,
  //   marginTop: scale(12),
  // },
  filterHeading: {
    fontSize: Size.font_18,
    fontFamily: Fonts.BOLD,
    color: colors.WHITE,
    paddingVertical: scale(5),
  },
  // leaveDates: {
  //   fontSize: Size.font_12,
  //   fontFamily: Fonts.MEDIUM,
  //   color: colors.GRAYTEXT,
  // },
  // leavePeriod: {
  //   fontSize: Size.font_12,
  //   fontFamily: Fonts.MEDIUM,
  //   color: colors.GRAYTEXT,
  //   paddingVertical: scale(5),
  // },
  // divider: {
  //   height: scale(1),
  //   marginVertical: scale(10),
  //   borderBottomColor: colors.Light_Purple2,
  //   borderBottomWidth: scale(0.25),
  // },
  // descriptionContainer: {
  //   marginTop: scale(10),
  //   padding: scale(16),
  //   borderWidth: 1,
  //   borderColor: colors.GRAYBORDER,
  //   borderRadius: 16,
  //   maxHeight: 150,
  //   height: 150,
  // },
  // descriptionText: {
  //   color: colors.GRAYTEXT,
  //   fontSize: Size.font_12,
  //   fontFamily: Fonts.MEDIUM,
  // },
  // statusButtonText: {
  //   width: '100%',
  //   fontSize: Size.font_20,
  //   fontFamily: Fonts.BOLD,
  //   textAlign: 'center',
  //   marginTop: scale(10),
  //   paddingVertical: scale(5),
  //   color: colors.WHITE,
  //   borderRadius: 20,
  //   marginTop: scale(30),
  // },
  formContainer1: {
    borderRadius: 16,
    backgroundColor: '#A2A2A21A',
    padding: scale(10),
    minHeight: 200,
  },
  formContainer2: {
    display: 'flex',
    flexDirection: 'row',
  },
  profile: {
    height: 50,
    width: 50,
    borderRadius: 50,
  },
  // formContainer2: {
  //   marginVertical: scale(5),
  //   padding: scale(16),
  //   borderWidth: 2,
  //   borderColor: '#DBDBDB',
  //   borderRadius: 16,
  //   backgroundColor: '#A2A2A21A',
  // },
  flexRow: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(5),
  },
  flexBetween: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: scale(10),
    paddingHorizontal: scale(5),
  },
  teacherName: {
    fontFamily: Fonts.BOLD,
    fontSize: Size.font_14,
    color: colors.WHITE,
    marginBottom: 1,
  },
  date: {
    fontFamily: Fonts.REGULAR,
    fontSize: Size.font_12,
    color: colors.COLOR_2,
    marginVertical: 1,
  },
  leftArrowIcon: {
    height: 12,
    width: 12,
    tintColor: colors.BLUE,
  },
  noticeDescription: {
    fontFamily: Fonts.REGULAR,
    fontSize: Size.font_14,
    color: colors.WHITE,
    marginLeft: scale(10),
    marginTop: scale(25),
  },
  notesIcon: {
    height: 24,
    width: 24,
    tintColor: 'white',
  },
  // postNotice: {
  //   fontFamily: Fonts.BOLD,
  //   fontSize: Size.font_14,
  // },
  noticeInput: {
    fontFamily: Fonts.REGULAR,
    fontSize: Size.font_14,
    flex: 1,
    paddingHorizontal: scale(10),
    maxHeight: 200,
    color: colors.BLACK,
  },
  // borderWidth: 1,
  // borderColor: 'gray',
  // postButtonContainer: {
  //   display: 'flex',
  //   flexDirection: 'row-reverse',
  //   justifyContent: 'space-between',
  //   alignItems: 'flex-end',
  //   marginTop: scale(10),
  //   gap: scale(5),
  // },
  toButton: {
    borderWidth: 1,
    borderColor: colors.COLOR_7,
    paddingVertical: scale(5),
    paddingHorizontal: scale(10),
    borderRadius: 20,
  },
  toButtonText: {
    fontFamily: Fonts.REGULAR,
    fontSize: Size.font_14,
    color: colors.BLUE,
  },
  cancelButton: {
    borderWidth: 1,
    borderColor: colors.COLOR_7,
    paddingVertical: scale(5),
    paddingHorizontal: scale(14),
    borderRadius: 20,
  },
  cancelButtonText: {
    fontFamily: Fonts.BOLD,
    fontSize: Size.font_14,
    color: colors.COLOR_7,
  },
  postButton: {
    backgroundColor: colors.COLOR_7,
    paddingVertical: scale(5),
    paddingHorizontal: scale(14),
    borderRadius: 20,
  },
  postButtonText: {
    fontFamily: Fonts.BOLD,
    fontSize: Size.font_14,
    color: colors.WHITE,
  },
  // cancelButton: {
  //   borderWidth: 1,
  //   borderColor: colors.COLOR_7,
  //   paddingVertical: scale(5),
  //   paddingHorizontal: scale(14),
  //   borderRadius: 20,
  // },
  // cancelText: {
  //   fontFamily: Fonts.BOLD,
  //   fontSize: Size.font_14,
  //   color: colors.COLOR_7,
  // },
  errorText: {
    color: colors.ORANGE,
    fontSize: Size.font_12,
    marginVertical: scale(5),
    marginLeft: scale(50),
    fontFamily: Fonts.REGULAR,
  },
  filterContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(5),
    paddingHorizontal: scale(16),
    paddingVertical: scale(10),
    marginVertical: scale(10),
    width: '80%',
  },
  filterIcon: {
    height: 32,
    width: 32,
  },
  refreshIcon: {
    height: 24,
    width: 24,
    marginRight: scale(10),
    tintColor: colors.BLUE,
  },
  filterText: {
    color: colors.BLUE,
    fontSize: Size.font_16,
    fontFamily: Fonts.BOLD,
  },
  divider: {
    height: scale(1),
    marginVertical: scale(15),
    borderBottomColor: colors.LINE,
    borderBottomWidth: 2,
  },
  // date: {
  //   color: colors.GRAYTEXT,
  //   fontSize: Size.font_12,
  //   fontFamily: Fonts.MEDIUM,
  //   marginTop: scale(5),
  // },
  // description: {
  //   color: colors.COLOR_8,
  //   fontSize: Size.font_14,
  //   fontFamily: Fonts.MEDIUM,
  //   marginTop: scale(5),
  // },
  // grayIconContainer: {
  //   width: 30,
  //   height: 30,
  //   backgroundColor: '#A2A2A240',
  //   display: 'flex',
  //   justifyContent: 'center',
  //   alignItems: 'center',
  //   borderRadius: 50,
  // },
  // updateDeleteIcon: {
  //   width: 18,
  //   height: 18,
  // },
  // schoolNameContainer: {
  //   display: 'flex',
  //   justifyContent: 'center',
  //   alignItems: 'center',
  //   backgroundColor: colors.COLOR_17,
  //   padding: scale(10),
  //   borderRadius: 5,
  // },
  // schoolNameText: {
  //   color: colors.BLACK,
  //   fontSize: Size.font_16,
  //   fontFamily: Fonts.BOLD,
  // },
  bottomSheet: {
    height: '30%',
    width: '100%',
    backgroundColor: '#383839',
    borderTopLeftRadius: scale(20),
    borderTopRightRadius: scale(20),
    padding: scale(10),
  },
  filterOptionContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: scale(10),
    paddingVertical: scale(10),
  },
  filterOptionText: {
    color: colors.BLUE,
    fontSize: Size.font_18,
    fontFamily: Fonts.BOLD,
  },
  noDataContainer: {
    height: '70%',
    width: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  noDataImg: {
    height: 300,
    width: 300,
  },
  noDataText: {
    color: colors.WHITE,
    fontFamily: Fonts.BOLD,
    fontSize: Size.font_20,
  },
});

export default styles;
