import {StyleSheet} from 'react-native';
import colors from '@src/theme/colors';
import {Size, Weight, Colors, Fonts} from '@src/theme/fonts';
import {scale} from 'react-native-size-matters';

const styles = StyleSheet.create({
  root: {flex: 1},
  container: {backgroundColor: colors.COLOR_6},
  loading: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    opacity: 0.5,
    zIndex: 10,
  },
  header: {
    flex: 1,
    // backgroundColor: colors.WHITE,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    borderBottomWidth: scale(1),
    borderBottomColor: colors.Light_Purple2,
    margin: scale(16),
    paddingBottom: scale(16),
  },
  headerContent: {
    // flexDirection: 'column',
    // justifyContent: 'space-between',
    // padding: scale(16),
    // backgroundColor: colors.WHITE,
  },
  nameText: {
    fontSize: Size.font_20,
    fontFamily: Fonts.BOLD,
    color: colors.INDIGO,
    paddingLeft: scale(0),
    marginTop: scale(-2),
  },
  dateText: {
    fontSize: Size.font_20,
    fontFamily: Fonts.BOLD,
    color: colors.GRAY2,
    marginTop: 2,
    paddingLeft: scale(0),
  },
  menuButton: {
    // height: 100,
    // width: 100,
    // position: 'absolute',
    // top: scale(16),
    // right: scale(16),
    // marginTop: scale(-3),
    // borderRadius: scale(4),
    // zIndex: 10,
  },
  menuText: {color: colors.PURPLE1, fontSize: 40},
  calendarContainer: {
    paddingTop: scale(20),
    paddingLeft: scale(2),
    paddingRight: scale(2),
    backgroundColor: colors.Light_Purple1,
    borderRadius: scale(30),
    margin: scale(16),
    shadowColor: colors.BLACK,
    shadowOpacity: 0.8,
    shadowRadius: scale(10),
  },
  calendarHeader: {flexDirection: 'row', marginBottom: scale(10)},
  monthText: {
    fontSize: Size.font_18,
    fontFamily: Fonts.BOLD,
    color: colors.INDIGO,
    paddingLeft: scale(13),
  },
  yearText: {
    fontSize: Size.font_18,
    fontFamily: Fonts.BOLD,
    color: colors.INDIGO,
  },
  attendanceSummaryContainer: {
    flex: 1,
    flexDirection: 'column',
    paddingHorizontal: scale(20),
    paddingVertical: scale(24),
    backgroundColor: colors.WHITE,
    borderRadius: scale(24),
    shadowColor: colors.BLACK,
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
    elevation: scale(2),
    textAlign: 'center',
    marginHorizontal: scale(15),
    marginBottom: scale(5),
  },
  attendanceHeaderText: {
    fontSize: Size.font_20,
    fontFamily: Fonts.BOLD,
    color: colors.INDIGO,
    left: scale(-5),
    top: scale(-5),
  },
  attendanceSubHeaderText: {
    fontSize: Size.font_16,
    fontFamily: Fonts.MEDIUM,
    color: colors.GRAY2,
    marginTop: scale(-5),
  },
  divider: {
    marginTop: scale(14),
    height: scale(1),
    backgroundColor: colors.LIGHT_PURPLE,
    opacity: 0.2,
  },
  summaryBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: scale(18),
    paddingVertical: scale(16),
    marginTop: scale(20),
    borderRadius: scale(12),
    backgroundColor: colors.LIGHT_GREEN,
  },
  summaryTextContainer: {flexDirection: 'column', alignItems: 'flex-start'},
  summaryTitleText: {
    fontFamily: Fonts.BOLD,
    color: colors.INDIGO,
    fontSize: Size.font_18,
  },
  summarySubtitleText: {
    marginTop: scale(10),
    fontFamily: Fonts.BOLD,
    color: colors.DARK_BLUE,
    opacity: 0.6,
    fontSize: Size.font_18,
  },
  summaryValueContainer: {flexDirection: 'column'},
  summaryValueText: {
    fontFamily: Fonts.BOLD,
    color: colors.GREEN,
    fontSize: Size.font_18,
    marginTop: scale(2),
  },
  summaryDaysText: {
    fontFamily: Fonts.BOLD,
    color: colors.GREEN,
    fontSize: Size.font_18,
    marginTop: scale(2),
  },
  sidebar: {
    position: 'absolute',
    right: scale(0),
    top: scale(0),
    bottom: scale(0),
    width: scale(256),
    backgroundColor: Colors.CREAM_WHITE,
    borderLeftWidth: 1,
    borderLeftColor: colors.WHITE,
    padding: scale(20),
    zIndex: 50,
  },
  sidebarHeader: {
    flexDirection: 'col',
    alignItems: 'center',
    marginBottom: scale(20),
  },
  sidebarHeadersub: {
    flexDirection: 'column',
    // top: scale(-10)
  },
  profileImage: {
    width: scale(100),
    height: scale(100),
    borderRadius: scale(50),
  },
  profileName: {
    fontSize: Size.font_18,
    fontFamily: Fonts.BOLD,
    color: colors.INDIGO,
    textAlign: 'center',
  },
  editPicIcon: {
    height: scale(18),
    width: scale(18),
    marginLeft: scale(1),
    top: scale(2),
    left: scale(1),
  },
  editPicButton: {
    backgroundColor: colors.LIGHT_PURPLE,
    borderRadius: 20,
    height: scale(27),
    width: scale(27),
    borderWidth: 2,
    borderColor: colors.WHITE,
    top: scale(-22),
    left: scale(24),
  },
  sidebarEdit: {
    borderRadius: scale(10),
    paddingHorizontal: scale(16),
    paddingVertical: scale(4),
    backgroundColor: colors.PURPLE11,
    marginTop: scale(5),
  },
  sidebarEditText: {
    fontSize: Size.font_14,
    color: colors.PURPLE1,
    fontFamily: Fonts.BOLD,
  },
  sidebarItem: {
    paddingVertical: scale(8),
    top: scale(0),
    flexDirection: 'row',
    paddingLeft: scale(10),
    alignItems: 'center',
    backgroundColor: colors.WHITE,
    borderRadius: scale(20),
  },
  sidebarItem1: {
    paddingVertical: scale(8),
    top: scale(0),
    flexDirection: 'row',
    paddingLeft: scale(10),
    alignItems: 'center',
    backgroundColor: colors.WHITE,
    borderRadius: scale(20),
    marginTop: scale(8),
  },
  sidebarItemImage: {
    width: 20,
    height: 20,
    resizeMode: 'contain',
    backgroundColor: colors.Light_Purple1,
    borderRadius: scale(10),
  },
  sidebarItemText: {
    fontSize: Size.font_14,
    color: colors.INDIGO,
    fontFamily: Fonts.BOLD,
    backgroundColor: colors.WHITE,
    padding: scale(4),
    borderRadius: scale(15),
    marginLeft: scale(8),
  },
  popup: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    backgroundColor: colors.WHITE,
    borderTopLeftRadius: scale(32),
    borderTopRightRadius: scale(32),
    shadowColor: colors.INDIGO,
    shadowOpacity: 0.8,
    shadowRadius: scale(100),
    elevation: scale(20),
    zIndex: 1000,
  },
  popupContent: {
    paddingTop: scale(16),
    paddingBottom: scale(64),
    paddingHorizontal: scale(16),
    backgroundColor: colors.WHITE,
    borderTopLeftRadius: scale(32),
    borderTopRightRadius: scale(32),
    shadowColor: colors.BLACK,
    shadowOpacity: 0.8,
    shadowRadius: scale(10),
  },
  popupButtonContainer: {
    display: 'flex',
    justifyContent: 'flex-end',
    width: '100%',
    alignItems: 'flex-end',
  },
  doneButton: {
    alignItems: 'center',
    paddingVertical: scale(5),
    backgroundColor: colors.PURPLE,
    borderRadius: scale(24),
    width: '20%',
  },
  doneButtonText: {
    color: colors.WHITE,
    fontFamily: Fonts.MEDIUM,
    fontSize: Size.font_16,
  },
  popupHeader: {marginLeft: scale(12), marginBottom: scale(5)},
  popupHeaderText: {
    fontSize: Size.font_20,
    fontFamily: Fonts.BOLD,
    color: colors.DARK_BLUE,
  },
  popupDateText: {
    fontSize: Size.font_20,
    color: colors.PURPLE,
    fontFamily: Fonts.MEDIUM,
    marginBottom: scale(20),
  },
  attendanceOptionsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: scale(-30),
  },
  attendanceOption: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: scale(12),
    borderRadius: scale(24),
    marginHorizontal: scale(8),
  },
  attendanceOptionText: {fontFamily: Fonts.BOLD, fontSize: Size.font_16},
  overlayContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    zIndex: 20,
    flexDirection: 'row',
  },
  overlay: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.1)',
    zIndex: 10,
  },
  modalContent: {
    width: '100%',
    padding: scale(20),
    backgroundColor: colors.WHITE,
    borderTopLeftRadius: scale(16),
    borderTopRightRadius: scale(16),
    elevation: 5,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'flex-end', // Align items to the bottom
    alignItems: 'center',
  },
});

export default styles;
