export const ROUTE = {
  SPLASH: 'Splash',
  LOGIN: 'Login',
  OTP: 'OTP',
  EMAIL_VERIFICATION: 'EmailVerification',
  EMAIL_OTP_VERIFICATION: 'Email_OTP',
  CREATE_PASSWORD: 'CreatePassword',
  SUCCESS_PAGE:'SuccessPage',
  PARENT_DETAIL:'ParentDetail',
  CHILD_DETAIL:"ChildDetail",
  HOME: 'Home',
  PROFILE: 'Profile',
  DASHBOARD: 'Dashboard',
  EVENT: 'Event',
 
  UPDATE_PASSWORD: 'UpdatePassword',
  AUTH: 'Auth',
  TAB: 'Tab',
  PARENT_EDIT: 'Parent_Edit',
  PARENT_PRIVACY: 'Parent_Privacy',
  PARENT_PROFILE_EDIT: 'Parent_Profile_Edit',
  FORGOTPASSWORD: 'ForgotPassword',
  EVENT_SEARCH:"EventSearch",
  EVENT_HOLIDAY:"EventHoliday"
};
