// All Routes Name
export const ROUTE = {
  SPLASH: 'Splash',
  LOGIN: 'Login',
  PHONE_NUMBER_VERIFICATION: 'PhoneNumberVerification',
  OTP: 'OTP',
  EMAIL_VERIFICATION: 'EmailVerification',
  EMAIL_OTP_VERIFICATION: 'Email_OTP',
  CREATE_PASSWORD: 'CreatePassword',
  SUCCESS_PAGE: 'SuccessPage',
  PARENT_DETAIL: 'ParentDetail',
  CHILD_DETAIL: 'ChildDetail',
  HOME: 'Home',
  EVENT: 'Event',
  PROFILE: 'Profile',
  DASHBOARD: 'Dashboard',
  EVENT: 'Event',
  CHILD: 'Child',
  CHILD_STACK: 'ChildTStack',
  EDIT_CHILD: 'EditChild',
  SETTING: 'Setting',
  EDIT_PROFILE: 'EditProfile',
  CHANGE_PASSWORD: 'ChangePassword',
  SETTING_STACK: 'SettingStack',
  DASHBOARD_STACK: 'DashboardStack',
  NOTICE: 'Notice',
  LEAVE: 'Leave',
  COMING_SOON: 'ComingSoon',

  UPDATE_PASSWORD: 'UpdatePassword',
  AUTH: 'Auth',
  TAB: 'Tab',
  PARENT_EDIT: 'Parent_Edit',
  PARENT_PRIVACY: 'Parent_Privacy',
  PARENT_PROFILE_EDIT: 'Parent_Profile_Edit',
  FORGOTPASSWORD: 'ForgotPassword',
  EVENT_SEARCH: 'EventSearch',
  EVENT_HOLIDAY: 'EventHoliday',
};
